version: 1

sources:
  - name: reed_jobs_data
    database: JOBSEEKER
    schema: raw
    tables:
      - name: REED_JOBS_DATA
  - name: dim_locations
    database: JOBSEEKER
    schema: serving
    tables:
      - name: dim_locations