jobseeker:
  outputs:
    ci:
      type: snowflake
      threads: 1
      account: TA30193.ap-southeast-2
      user: DBT
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: DBT_RW
      warehouse: ETL
      database: JOBSEEKER
      schema: RAW
    prod:
      type: snowflake
      threads: 1
      account: TA30193.ap-southeast-2
      user: DBT
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: DBT_RW
      warehouse: ETL
      database: JOBSEEKER
      schema: RAW
  target: prod