name: linter
on:
  # Can be manually triggered
  workflow_dispatch: {}
  # Triggered on each pull request to main
  pull_request:
    branches: [ main ]

jobs:
  linter:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-bookworm

    env:
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}

    steps:
      - name: Checkout code repository in agent
        uses: actions/checkout@v4
        with:
          set-safe-directory: true

      # https://github.com/actions/runner/issues/2033#issuecomment-1204205989
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./airflow/dags/dbt/requirements.txt

      - name: Debug DBT_PASSWORD
        run: |
          echo "DBT_PASSWORD: $DBT_PASSWORD"

      - name: Run linting checks. Exit code 1 if linter failed
        run: |
          bash ./bin/linter.sh
